const CREST = "/brand/sports/crests";
const NBA = "/brand/sports/nba";
const TENNIS = "/brand/sports/tennis";

const FILES: Record<string, string> = {
  "ac milan": `${CREST}/ac-milan.webp`,
  milan: `${CREST}/ac-milan.webp`,
  "inter milan": `${CREST}/inter-milan.webp`,
  inter: `${CREST}/inter-milan.webp`,
  juventus: `${CREST}/juventus.webp`,
  napoli: `${CREST}/napoli.webp`,
  roma: `${CREST}/roma.webp`,
  lazio: `${CREST}/lazio.webp`,
  atalanta: `${CREST}/atalanta.webp`,
  fiorentina: `${CREST}/fiorentina.webp`,
  bologna: `${CREST}/bologna.webp`,
  torino: `${CREST}/torino.webp`,
  genoa: `${CREST}/genoa.webp`,
  udinese: `${CREST}/udinese.webp`,
  cagliari: `${CREST}/cagliari.webp`,
  lecce: `${CREST}/lecce.webp`,
  parma: `${CREST}/parma.webp`,
  como: `${CREST}/como-1907.webp`,
  "como 1907": `${CREST}/como-1907.webp`,
  sassuolo: `${CREST}/sassuolo.webp`,
  venezia: `${CREST}/venezia-fc.webp`,
  monza: `${CREST}/ac-monza.webp`,
  arsenal: `${CREST}/arsenal.webp`,
  chelsea: `${CREST}/chelsea.webp`,
  liverpool: `${CREST}/liverpool-fc.webp`,
  "liverpool fc": `${CREST}/liverpool-fc.webp`,
  "manchester city": `${CREST}/manchester-city.webp`,
  "man city": `${CREST}/manchester-city.webp`,
  "manchester united": `${CREST}/manchester-united.webp`,
  "man united": `${CREST}/manchester-united.webp`,
  tottenham: `${CREST}/tottenham-hotspur.webp`,
  "tottenham hotspur": `${CREST}/tottenham-hotspur.webp`,
  "newcastle united": `${CREST}/newcastle-united.webp`,
  newcastle: `${CREST}/newcastle-united.webp`,
  "aston villa": `${CREST}/aston-villa.webp`,
  everton: `${CREST}/everton.webp`,
  fulham: `${CREST}/fulham.webp`,
  brentford: `${CREST}/brentford.webp`,
  brighton: `${CREST}/brighton-and-hove-albion.webp`,
  "crystal palace": `${CREST}/crystal-palace.webp`,
  bournemouth: `${CREST}/afc-bournemouth.webp`,
  "real madrid": `${CREST}/real-madrid.webp`,
  barcelona: `${CREST}/fc-barcelona.webp`,
  "fc barcelona": `${CREST}/fc-barcelona.webp`,
  "atletico madrid": `${CREST}/real-madrid.webp`,
  sevilla: `${CREST}/sevilla-fc.webp`,
  "real sociedad": `${CREST}/real-sociedad.webp`,
  "real betis": `${CREST}/real-betis-balompie.webp`,
  villarreal: `${CREST}/villarreal-cf.webp`,
  "celta vigo": `${CREST}/celta-vigo.webp`,
  "bayern munich": `${CREST}/bayern-munich.webp`,
  bayern: `${CREST}/bayern-munich.webp`,
  "borussia dortmund": `${CREST}/borussia-dortmund.webp`,
  dortmund: `${CREST}/borussia-dortmund.webp`,
  "bayer leverkusen": `${CREST}/bayer-leverkusen.webp`,
  "rb leipzig": `${CREST}/rb-leipzig.webp`,
  stuttgart: `${CREST}/vfb-stuttgart.webp`,
  "paris saint-germain": `${CREST}/paris-saint-germain-psg.webp`,
  psg: `${CREST}/paris-saint-germain-psg.webp`,
  ajax: `${CREST}/ajax.webp`,
  "psv eindhoven": `${CREST}/psv-eindhoven.webp`,
  psv: `${CREST}/psv-eindhoven.webp`,
  feyenoord: `${CREST}/feyenoord.webp`,
  porto: `${CREST}/fc-porto.webp`,
  "fc porto": `${CREST}/fc-porto.webp`,
  "sporting cp": `${CREST}/sporting-cp.webp`,
  sporting: `${CREST}/sporting-cp.webp`,
  galatasaray: `${CREST}/galatasaray.webp`,
  "shakhtar donetsk": `${CREST}/shakhtar-donetsk.webp`,
  "club brugge": `${CREST}/club-brugge.webp`,
  lille: `${CREST}/losc-lille.webp`,
  "atlanta hawks": `${NBA}/atlanta-hawks.svg`,
  hawks: `${NBA}/atlanta-hawks.svg`,
  "boston celtics": `${NBA}/boston-celtics.svg`,
  celtics: `${NBA}/boston-celtics.svg`,
  "brooklyn nets": `${NBA}/brooklyn-nets.svg`,
  nets: `${NBA}/brooklyn-nets.svg`,
  "charlotte hornets": `${NBA}/charlotte-hornets.svg`,
  hornets: `${NBA}/charlotte-hornets.svg`,
  "chicago bulls": `${NBA}/chicago-bulls.svg`,
  bulls: `${NBA}/chicago-bulls.svg`,
  "cleveland cavaliers": `${NBA}/cleveland-cavaliers.svg`,
  cavaliers: `${NBA}/cleveland-cavaliers.svg`,
  cavs: `${NBA}/cleveland-cavaliers.svg`,
  "dallas mavericks": `${NBA}/dallas-mavericks.svg`,
  mavericks: `${NBA}/dallas-mavericks.svg`,
  "denver nuggets": `${NBA}/denver-nuggets.svg`,
  nuggets: `${NBA}/denver-nuggets.svg`,
  "detroit pistons": `${NBA}/detroit-pistons.svg`,
  pistons: `${NBA}/detroit-pistons.svg`,
  "golden state warriors": `${NBA}/golden-state-warriors.svg`,
  warriors: `${NBA}/golden-state-warriors.svg`,
  "houston rockets": `${NBA}/houston-rockets.svg`,
  rockets: `${NBA}/houston-rockets.svg`,
  "indiana pacers": `${NBA}/indiana-pacers.svg`,
  pacers: `${NBA}/indiana-pacers.svg`,
  "la clippers": `${NBA}/la-clippers.svg`,
  "los angeles clippers": `${NBA}/la-clippers.svg`,
  clippers: `${NBA}/la-clippers.svg`,
  "los angeles lakers": `${NBA}/los-angeles-lakers.svg`,
  lakers: `${NBA}/los-angeles-lakers.svg`,
  "memphis grizzlies": `${NBA}/memphis-grizzlies.svg`,
  grizzlies: `${NBA}/memphis-grizzlies.svg`,
  "miami heat": `${NBA}/miami-heat.svg`,
  heat: `${NBA}/miami-heat.svg`,
  "milwaukee bucks": `${NBA}/milwaukee-bucks.svg`,
  bucks: `${NBA}/milwaukee-bucks.svg`,
  "minnesota timberwolves": `${NBA}/minnesota-timberwolves.svg`,
  timberwolves: `${NBA}/minnesota-timberwolves.svg`,
  "new orleans pelicans": `${NBA}/new-orleans-pelicans.svg`,
  pelicans: `${NBA}/new-orleans-pelicans.svg`,
  "new york knicks": `${NBA}/new-york-knicks.svg`,
  knicks: `${NBA}/new-york-knicks.svg`,
  "oklahoma city thunder": `${NBA}/okc-thunder.svg`,
  thunder: `${NBA}/okc-thunder.svg`,
  okc: `${NBA}/okc-thunder.svg`,
  "orlando magic": `${NBA}/orlando-magic.svg`,
  magic: `${NBA}/orlando-magic.svg`,
  "phoenix suns": `${NBA}/phoenix-suns.svg`,
  suns: `${NBA}/phoenix-suns.svg`,
  "portland trail blazers": `${NBA}/portland-trail-blazers.svg`,
  "trail blazers": `${NBA}/portland-trail-blazers.svg`,
  "sacramento kings": `${NBA}/sacramento-kings.svg`,
  kings: `${NBA}/sacramento-kings.svg`,
  "san antonio spurs": `${NBA}/san-antonio-spurs.svg`,
  spurs: `${NBA}/san-antonio-spurs.svg`,
  "toronto raptors": `${NBA}/toronto-raptors.svg`,
  raptors: `${NBA}/toronto-raptors.svg`,
  "utah jazz": `${NBA}/utah-jazz.svg`,
  jazz: `${NBA}/utah-jazz.svg`,
  "washington wizards": `${NBA}/washington-wizards.svg`,
  wizards: `${NBA}/washington-wizards.svg`,
  "jannik sinner": `${TENNIS}/sinner.png`,
  sinner: `${TENNIS}/sinner.png`,
  "carlos alcaraz": `${TENNIS}/alcaraz.png`,
  alcaraz: `${TENNIS}/alcaraz.png`,
  "novak djokovic": `${TENNIS}/djokovic.png`,
  djokovic: `${TENNIS}/djokovic.png`,
  "alexander zverev": `${TENNIS}/zverev.png`,
  zverev: `${TENNIS}/zverev.png`,
  "daniil medvedev": `${TENNIS}/medvedev.png`,
  medvedev: `${TENNIS}/medvedev.png`,
  "taylor fritz": `${TENNIS}/fritz.png`,
  fritz: `${TENNIS}/fritz.png`,
  "ben shelton": `${TENNIS}/shelton.png`,
  shelton: `${TENNIS}/shelton.png`,
  "alex de minaur": `${TENNIS}/de-minaur.png`,
  "de minaur": `${TENNIS}/de-minaur.png`,
  "flavio cobolli": `${TENNIS}/cobolli.png`,
  cobolli: `${TENNIS}/cobolli.png`,
  "felix auger-aliassime": `${TENNIS}/auger-aliassime.png`,
  "auger-aliassime": `${TENNIS}/auger-aliassime.png`,
};

const LEAGUES: Record<string, string> = {
  "serie a": `${CREST}/serie-a-italy.svg`,
  "premier league": `${CREST}/premier-league-england.webp`,
  "la liga": `${CREST}/laliga-spain.webp`,
  bundesliga: `${CREST}/bundesliga-germany.webp`,
  "champions league": `${CREST}/uefa-champions-league.svg`,
  "uefa champions league": `${CREST}/uefa-champions-league.svg`,
  atp: `${TENNIS}/atp.svg`,
  "atp 500": `${TENNIS}/atp.svg`,
  "atp tour": `${TENNIS}/atp.svg`,
};

function key(name: string) {
  return name.trim().toLowerCase();
}

export function clubCrest(name: string): string | undefined {
  return FILES[key(name)];
}

export function leagueCrest(name: string): string | undefined {
  return LEAGUES[key(name)];
}
