/** Hero lobby slides — 16 Sep art pack (1.jpg–6.jpg) mapped onto public/brand slots. */

export const HERO_SLIDES = [
  {
    id: "obsidian-blackjack",
    kicker: "TOLS",
    titleLime: "TOLS",
    titleRest: "ORIGINALS",
    subtitle: "18+ · originals · play responsibly",
    cta: "PLAY",
    image: "/brand/affiliate/hero-brand.jpg",
    position: "center",
    alt: "TOLS hero — chips and official T mark",
  },
  {
    id: "signal-dice",
    kicker: "DICE",
    titleLime: "SIGNAL",
    titleRest: "DICE",
    subtitle: "Roll under or over. Instant.",
    cta: "BET",
    image: "/brand/promo/rakeback.jpg",
    position: "center",
    alt: "TOLS dice and coins banner",
  },
  {
    id: "crazy-tols",
    kicker: "CRAZY TOLS",
    titleLime: "CRAZY",
    titleRest: "TOLS",
    subtitle: "Money wheel · 4 bonus rounds · Top Slot",
    cta: "SPIN",
    image: "/brand/promo/clutch.jpg",
    position: "center",
    alt: "TOLS queen cards banner",
  },
  {
    id: "obsidian-blackjack",
    slideKey: "hands",
    kicker: "BLACKJACK",
    titleLime: "FELT",
    titleRest: "NIGHT",
    subtitle: "Dealer stands on 17. Blackjack pays 3:2.",
    cta: "DEAL",
    image: "/brand/promo/cashback.jpg",
    position: "center",
    alt: "TOLS hands and crown banner",
  },
  {
    id: "neon-crash",
    kicker: "RACE",
    titleLime: "WEEKLY",
    titleRest: "RACE",
    subtitle: "Paid bets only. Leaderboard resets Monday.",
    cta: "PLAY",
    image: "/brand/promo/race.jpg",
    position: "center",
    alt: "TOLS trophy banner",
  },
  {
    id: "obsidian-blackjack",
    slideKey: "aces",
    kicker: "TABLE",
    titleLime: "ACES",
    titleRest: "UP",
    subtitle: "Originals blackjack on the TOLS felt.",
    cta: "DEAL",
    image: "/brand/promo/jackpot.jpg",
    position: "center",
    alt: "TOLS aces blackjack banner",
  },
] as const;
