/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAffiliateRouteImport } from './routes/_shell/affiliate'
import { Route as ShellAlertsRouteImport } from './routes/_shell/alerts'
import { Route as ShellAmlRouteImport } from './routes/_shell/aml'
import { Route as ShellCasinoRouteImport } from './routes/_shell/casino'
import { Route as ShellConnectRouteImport } from './routes/_shell/connect'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellFairnessRouteImport } from './routes/_shell/fairness'
import { Route as ShellHelpRouteImport } from './routes/_shell/help'
import { Route as ShellLiveRouteImport } from './routes/_shell/live'
import { Route as ShellOriginalsRouteImport } from './routes/_shell/originals'
import { Route as ShellPrivacyRouteImport } from './routes/_shell/privacy'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellPromotionsRouteImport } from './routes/_shell/promotions'
import { Route as ShellRedeemRouteImport } from './routes/_shell/redeem'
import { Route as ShellResponsibleRouteImport } from './routes/_shell/responsible'
import { Route as ShellSportsRouteImport } from './routes/_shell/sports'
import { Route as ShellTermsRouteImport } from './routes/_shell/terms'
import { Route as ShellTokenRouteImport } from './routes/_shell/token'
import { Route as ShellVaultRouteImport } from './routes/_shell/vault'
import { Route as ShellVipRouteImport } from './routes/_shell/vip'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPlatformRouteImport } from './routes/api/platform'
import { Route as ApiTreasuryRouteImport } from './routes/api/treasury'
import { Route as ShellGamesIdRouteImport } from './routes/_shell/games.$id'
import { Route as ShellOriginalsIdRouteImport } from './routes/_shell/originals.$id'
import { Route as ShellPlaySlugRouteImport } from './routes/_shell/play.$slug'
import { Route as ShellSportsIdRouteImport } from './routes/_shell/sports.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiBridgeHealthRouteImport } from './routes/api/bridge/health'
import { Route as ApiBridgeWebhookRouteImport } from './routes/api/bridge/webhook'
import { Route as ApiFlexrixCallbackRouteImport } from './routes/api/flexrix/callback'
import { Route as ApiFlexrixLaunchDemoRouteImport } from './routes/api/flexrix/launch-demo'
import { Route as ApiOperatorCallbackRouteImport } from './routes/api/operator/callback'
import { Route as ApiOperatorGamesRouteImport } from './routes/api/operator/games'
import { Route as ApiOperatorLaunchRouteImport } from './routes/api/operator/launch'
import { Route as ApiOperatorPaymentsRouteImport } from './routes/api/operator/payments'
import { Route as ApiOperatorSkillsRouteImport } from './routes/api/operator/skills'
import { Route as ApiOperatorStatusRouteImport } from './routes/api/operator/status'
import { Route as ApiOperatorWalletRouteImport } from './routes/api/operator/wallet'
import { Route as ApiPlatformHealthRouteImport } from './routes/api/platform/health'
import { Route as ApiPlatformWhoamiRouteImport } from './routes/api/platform/whoami'
import { Route as ApiSelftestSportTicketRouteImport } from './routes/api/selftest/sport-ticket'
import { Route as ApiSportsbookCallbackRouteImport } from './routes/api/sportsbook/callback'
import { Route as ApiSportsbookEventsRouteImport } from './routes/api/sportsbook/events'
import { Route as ApiSportsbookScoresRouteImport } from './routes/api/sportsbook/scores'
import { Route as ApiSportsbookSessionRouteImport } from './routes/api/sportsbook/session'
import { Route as ApiSportsbookSettleRouteImport } from './routes/api/sportsbook/settle'
import { Route as ApiSportsbookSportsRouteImport } from './routes/api/sportsbook/sports'
import { Route as ShellSportsClubSlugRouteImport } from './routes/_shell/sports.club.$slug'
import { Route as ShellSportsPlayerSlugRouteImport } from './routes/_shell/sports.player.$slug'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'
import { Route as ApiAuthGoogleDiagRouteImport } from './routes/api/auth/google.diag'
import { Route as ApiSportsbookCallbackActionRouteImport } from './routes/api/sportsbook/callback.$action'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAffiliateRoute = ShellAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlertsRoute = ShellAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAmlRoute = ShellAmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCasinoRoute = ShellCasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectRoute = ShellConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFairnessRoute = ShellFairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLiveRoute = ShellLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOriginalsRoute = ShellOriginalsRouteImport.update({
  id: '/originals',
  path: '/originals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPrivacyRoute = ShellPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPromotionsRoute = ShellPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRedeemRoute = ShellRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResponsibleRoute = ShellResponsibleRouteImport.update({
  id: '/responsible',
  path: '/responsible',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSportsRoute = ShellSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTermsRoute = ShellTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTokenRoute = ShellTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVaultRoute = ShellVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVipRoute = ShellVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => ShellRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformRoute = ApiPlatformRouteImport.update({
  id: '/api/platform',
  path: '/api/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTreasuryRoute = ApiTreasuryRouteImport.update({
  id: '/api/treasury',
  path: '/api/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellGamesIdRoute = ShellGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOriginalsIdRoute = ShellOriginalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellOriginalsRoute,
} as any)
const ShellPlaySlugRoute = ShellPlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSportsIdRoute = ShellSportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellSportsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeHealthRoute = ApiBridgeHealthRouteImport.update({
  id: '/api/bridge/health',
  path: '/api/bridge/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeWebhookRoute = ApiBridgeWebhookRouteImport.update({
  id: '/api/bridge/webhook',
  path: '/api/bridge/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlexrixCallbackRoute = ApiFlexrixCallbackRouteImport.update({
  id: '/api/flexrix/callback',
  path: '/api/flexrix/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlexrixLaunchDemoRoute = ApiFlexrixLaunchDemoRouteImport.update({
  id: '/api/flexrix/launch-demo',
  path: '/api/flexrix/launch-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorCallbackRoute = ApiOperatorCallbackRouteImport.update({
  id: '/api/operator/callback',
  path: '/api/operator/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorGamesRoute = ApiOperatorGamesRouteImport.update({
  id: '/api/operator/games',
  path: '/api/operator/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorLaunchRoute = ApiOperatorLaunchRouteImport.update({
  id: '/api/operator/launch',
  path: '/api/operator/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorPaymentsRoute = ApiOperatorPaymentsRouteImport.update({
  id: '/api/operator/payments',
  path: '/api/operator/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorSkillsRoute = ApiOperatorSkillsRouteImport.update({
  id: '/api/operator/skills',
  path: '/api/operator/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorStatusRoute = ApiOperatorStatusRouteImport.update({
  id: '/api/operator/status',
  path: '/api/operator/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorWalletRoute = ApiOperatorWalletRouteImport.update({
  id: '/api/operator/wallet',
  path: '/api/operator/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformHealthRoute = ApiPlatformHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiPlatformRoute,
} as any)
const ApiPlatformWhoamiRoute = ApiPlatformWhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => ApiPlatformRoute,
} as any)
const ApiSelftestSportTicketRoute = ApiSelftestSportTicketRouteImport.update({
  id: '/api/selftest/sport-ticket',
  path: '/api/selftest/sport-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookCallbackRoute = ApiSportsbookCallbackRouteImport.update({
  id: '/api/sportsbook/callback',
  path: '/api/sportsbook/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookEventsRoute = ApiSportsbookEventsRouteImport.update({
  id: '/api/sportsbook/events',
  path: '/api/sportsbook/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookScoresRoute = ApiSportsbookScoresRouteImport.update({
  id: '/api/sportsbook/scores',
  path: '/api/sportsbook/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookSessionRoute = ApiSportsbookSessionRouteImport.update({
  id: '/api/sportsbook/session',
  path: '/api/sportsbook/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookSettleRoute = ApiSportsbookSettleRouteImport.update({
  id: '/api/sportsbook/settle',
  path: '/api/sportsbook/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsbookSportsRoute = ApiSportsbookSportsRouteImport.update({
  id: '/api/sportsbook/sports',
  path: '/api/sportsbook/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSportsClubSlugRoute = ShellSportsClubSlugRouteImport.update({
  id: '/club/$slug',
  path: '/club/$slug',
  getParentRoute: () => ShellSportsRoute,
} as any)
const ShellSportsPlayerSlugRoute = ShellSportsPlayerSlugRouteImport.update({
  id: '/player/$slug',
  path: '/player/$slug',
  getParentRoute: () => ShellSportsRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAuthGoogleDiagRoute = ApiAuthGoogleDiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiSportsbookCallbackActionRoute =
  ApiSportsbookCallbackActionRouteImport.update({
    id: '/$action',
    path: '/$action',
    getParentRoute: () => ApiSportsbookCallbackRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/affiliate': typeof ShellAffiliateRoute
  '/alerts': typeof ShellAlertsRoute
  '/aml': typeof ShellAmlRoute
  '/casino': typeof ShellCasinoRoute
  '/connect': typeof ShellConnectRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fairness': typeof ShellFairnessRoute
  '/help': typeof ShellHelpRoute
  '/live': typeof ShellLiveRoute
  '/originals': typeof ShellOriginalsRouteWithChildren
  '/privacy': typeof ShellPrivacyRoute
  '/profile': typeof ShellProfileRoute
  '/promotions': typeof ShellPromotionsRoute
  '/redeem': typeof ShellRedeemRoute
  '/responsible': typeof ShellResponsibleRoute
  '/sports': typeof ShellSportsRouteWithChildren
  '/terms': typeof ShellTermsRoute
  '/token': typeof ShellTokenRoute
  '/vault': typeof ShellVaultRoute
  '/vip': typeof ShellVipRoute
  '/api/health': typeof ApiHealthRoute
  '/api/platform': typeof ApiPlatformRouteWithChildren
  '/api/treasury': typeof ApiTreasuryRoute
  '/games/$id': typeof ShellGamesIdRoute
  '/originals/$id': typeof ShellOriginalsIdRoute
  '/play/$slug': typeof ShellPlaySlugRoute
  '/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bridge/health': typeof ApiBridgeHealthRoute
  '/api/bridge/webhook': typeof ApiBridgeWebhookRoute
  '/api/flexrix/callback': typeof ApiFlexrixCallbackRoute
  '/api/flexrix/launch-demo': typeof ApiFlexrixLaunchDemoRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/status': typeof ApiOperatorStatusRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
  '/api/platform/health': typeof ApiPlatformHealthRoute
  '/api/platform/whoami': typeof ApiPlatformWhoamiRoute
  '/api/selftest/sport-ticket': typeof ApiSelftestSportTicketRoute
  '/api/sportsbook/callback': typeof ApiSportsbookCallbackRouteWithChildren
  '/api/sportsbook/events': typeof ApiSportsbookEventsRoute
  '/api/sportsbook/scores': typeof ApiSportsbookScoresRoute
  '/api/sportsbook/session': typeof ApiSportsbookSessionRoute
  '/api/sportsbook/settle': typeof ApiSportsbookSettleRoute
  '/api/sportsbook/sports': typeof ApiSportsbookSportsRoute
  '/sports/club/$slug': typeof ShellSportsClubSlugRoute
  '/sports/player/$slug': typeof ShellSportsPlayerSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/diag': typeof ApiAuthGoogleDiagRoute
  '/api/sportsbook/callback/$action': typeof ApiSportsbookCallbackActionRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/affiliate': typeof ShellAffiliateRoute
  '/alerts': typeof ShellAlertsRoute
  '/aml': typeof ShellAmlRoute
  '/casino': typeof ShellCasinoRoute
  '/connect': typeof ShellConnectRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fairness': typeof ShellFairnessRoute
  '/help': typeof ShellHelpRoute
  '/live': typeof ShellLiveRoute
  '/originals': typeof ShellOriginalsRouteWithChildren
  '/privacy': typeof ShellPrivacyRoute
  '/profile': typeof ShellProfileRoute
  '/promotions': typeof ShellPromotionsRoute
  '/redeem': typeof ShellRedeemRoute
  '/responsible': typeof ShellResponsibleRoute
  '/sports': typeof ShellSportsRouteWithChildren
  '/terms': typeof ShellTermsRoute
  '/token': typeof ShellTokenRoute
  '/vault': typeof ShellVaultRoute
  '/vip': typeof ShellVipRoute
  '/api/health': typeof ApiHealthRoute
  '/api/platform': typeof ApiPlatformRouteWithChildren
  '/api/treasury': typeof ApiTreasuryRoute
  '/': typeof ShellIndexRoute
  '/games/$id': typeof ShellGamesIdRoute
  '/originals/$id': typeof ShellOriginalsIdRoute
  '/play/$slug': typeof ShellPlaySlugRoute
  '/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bridge/health': typeof ApiBridgeHealthRoute
  '/api/bridge/webhook': typeof ApiBridgeWebhookRoute
  '/api/flexrix/callback': typeof ApiFlexrixCallbackRoute
  '/api/flexrix/launch-demo': typeof ApiFlexrixLaunchDemoRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/status': typeof ApiOperatorStatusRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
  '/api/platform/health': typeof ApiPlatformHealthRoute
  '/api/platform/whoami': typeof ApiPlatformWhoamiRoute
  '/api/selftest/sport-ticket': typeof ApiSelftestSportTicketRoute
  '/api/sportsbook/callback': typeof ApiSportsbookCallbackRouteWithChildren
  '/api/sportsbook/events': typeof ApiSportsbookEventsRoute
  '/api/sportsbook/scores': typeof ApiSportsbookScoresRoute
  '/api/sportsbook/session': typeof ApiSportsbookSessionRoute
  '/api/sportsbook/settle': typeof ApiSportsbookSettleRoute
  '/api/sportsbook/sports': typeof ApiSportsbookSportsRoute
  '/sports/club/$slug': typeof ShellSportsClubSlugRoute
  '/sports/player/$slug': typeof ShellSportsPlayerSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/diag': typeof ApiAuthGoogleDiagRoute
  '/api/sportsbook/callback/$action': typeof ApiSportsbookCallbackActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/affiliate': typeof ShellAffiliateRoute
  '/_shell/alerts': typeof ShellAlertsRoute
  '/_shell/aml': typeof ShellAmlRoute
  '/_shell/casino': typeof ShellCasinoRoute
  '/_shell/connect': typeof ShellConnectRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/fairness': typeof ShellFairnessRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/live': typeof ShellLiveRoute
  '/_shell/originals': typeof ShellOriginalsRouteWithChildren
  '/_shell/privacy': typeof ShellPrivacyRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/promotions': typeof ShellPromotionsRoute
  '/_shell/redeem': typeof ShellRedeemRoute
  '/_shell/responsible': typeof ShellResponsibleRoute
  '/_shell/sports': typeof ShellSportsRouteWithChildren
  '/_shell/terms': typeof ShellTermsRoute
  '/_shell/token': typeof ShellTokenRoute
  '/_shell/vault': typeof ShellVaultRoute
  '/_shell/vip': typeof ShellVipRoute
  '/api/health': typeof ApiHealthRoute
  '/api/platform': typeof ApiPlatformRouteWithChildren
  '/api/treasury': typeof ApiTreasuryRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/games/$id': typeof ShellGamesIdRoute
  '/_shell/originals/$id': typeof ShellOriginalsIdRoute
  '/_shell/play/$slug': typeof ShellPlaySlugRoute
  '/_shell/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bridge/health': typeof ApiBridgeHealthRoute
  '/api/bridge/webhook': typeof ApiBridgeWebhookRoute
  '/api/flexrix/callback': typeof ApiFlexrixCallbackRoute
  '/api/flexrix/launch-demo': typeof ApiFlexrixLaunchDemoRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/status': typeof ApiOperatorStatusRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
  '/api/platform/health': typeof ApiPlatformHealthRoute
  '/api/platform/whoami': typeof ApiPlatformWhoamiRoute
  '/api/selftest/sport-ticket': typeof ApiSelftestSportTicketRoute
  '/api/sportsbook/callback': typeof ApiSportsbookCallbackRouteWithChildren
  '/api/sportsbook/events': typeof ApiSportsbookEventsRoute
  '/api/sportsbook/scores': typeof ApiSportsbookScoresRoute
  '/api/sportsbook/session': typeof ApiSportsbookSessionRoute
  '/api/sportsbook/settle': typeof ApiSportsbookSettleRoute
  '/api/sportsbook/sports': typeof ApiSportsbookSportsRoute
  '/_shell/sports/club/$slug': typeof ShellSportsClubSlugRoute
  '/_shell/sports/player/$slug': typeof ShellSportsPlayerSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/diag': typeof ApiAuthGoogleDiagRoute
  '/api/sportsbook/callback/$action': typeof ApiSportsbookCallbackActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/affiliate'
    | '/alerts'
    | '/aml'
    | '/casino'
    | '/connect'
    | '/dashboard'
    | '/fairness'
    | '/help'
    | '/live'
    | '/originals'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/redeem'
    | '/responsible'
    | '/sports'
    | '/terms'
    | '/token'
    | '/vault'
    | '/vip'
    | '/api/health'
    | '/api/platform'
    | '/api/treasury'
    | '/games/$id'
    | '/originals/$id'
    | '/play/$slug'
    | '/sports/$id'
    | '/api/auth/$'
    | '/api/auth/google'
    | '/api/auth/me'
    | '/api/bridge/health'
    | '/api/bridge/webhook'
    | '/api/flexrix/callback'
    | '/api/flexrix/launch-demo'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/status'
    | '/api/operator/wallet'
    | '/api/platform/health'
    | '/api/platform/whoami'
    | '/api/selftest/sport-ticket'
    | '/api/sportsbook/callback'
    | '/api/sportsbook/events'
    | '/api/sportsbook/scores'
    | '/api/sportsbook/session'
    | '/api/sportsbook/settle'
    | '/api/sportsbook/sports'
    | '/sports/club/$slug'
    | '/sports/player/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/diag'
    | '/api/sportsbook/callback/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/affiliate'
    | '/alerts'
    | '/aml'
    | '/casino'
    | '/connect'
    | '/dashboard'
    | '/fairness'
    | '/help'
    | '/live'
    | '/originals'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/redeem'
    | '/responsible'
    | '/sports'
    | '/terms'
    | '/token'
    | '/vault'
    | '/vip'
    | '/api/health'
    | '/api/platform'
    | '/api/treasury'
    | '/'
    | '/games/$id'
    | '/originals/$id'
    | '/play/$slug'
    | '/sports/$id'
    | '/api/auth/$'
    | '/api/auth/google'
    | '/api/auth/me'
    | '/api/bridge/health'
    | '/api/bridge/webhook'
    | '/api/flexrix/callback'
    | '/api/flexrix/launch-demo'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/status'
    | '/api/operator/wallet'
    | '/api/platform/health'
    | '/api/platform/whoami'
    | '/api/selftest/sport-ticket'
    | '/api/sportsbook/callback'
    | '/api/sportsbook/events'
    | '/api/sportsbook/scores'
    | '/api/sportsbook/session'
    | '/api/sportsbook/settle'
    | '/api/sportsbook/sports'
    | '/sports/club/$slug'
    | '/sports/player/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/diag'
    | '/api/sportsbook/callback/$action'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/affiliate'
    | '/_shell/alerts'
    | '/_shell/aml'
    | '/_shell/casino'
    | '/_shell/connect'
    | '/_shell/dashboard'
    | '/_shell/fairness'
    | '/_shell/help'
    | '/_shell/live'
    | '/_shell/originals'
    | '/_shell/privacy'
    | '/_shell/profile'
    | '/_shell/promotions'
    | '/_shell/redeem'
    | '/_shell/responsible'
    | '/_shell/sports'
    | '/_shell/terms'
    | '/_shell/token'
    | '/_shell/vault'
    | '/_shell/vip'
    | '/api/health'
    | '/api/platform'
    | '/api/treasury'
    | '/_shell/'
    | '/_shell/games/$id'
    | '/_shell/originals/$id'
    | '/_shell/play/$slug'
    | '/_shell/sports/$id'
    | '/api/auth/$'
    | '/api/auth/google'
    | '/api/auth/me'
    | '/api/bridge/health'
    | '/api/bridge/webhook'
    | '/api/flexrix/callback'
    | '/api/flexrix/launch-demo'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/status'
    | '/api/operator/wallet'
    | '/api/platform/health'
    | '/api/platform/whoami'
    | '/api/selftest/sport-ticket'
    | '/api/sportsbook/callback'
    | '/api/sportsbook/events'
    | '/api/sportsbook/scores'
    | '/api/sportsbook/session'
    | '/api/sportsbook/settle'
    | '/api/sportsbook/sports'
    | '/_shell/sports/club/$slug'
    | '/_shell/sports/player/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/diag'
    | '/api/sportsbook/callback/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPlatformRoute: typeof ApiPlatformRouteWithChildren
  ApiTreasuryRoute: typeof ApiTreasuryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiBridgeHealthRoute: typeof ApiBridgeHealthRoute
  ApiBridgeWebhookRoute: typeof ApiBridgeWebhookRoute
  ApiFlexrixCallbackRoute: typeof ApiFlexrixCallbackRoute
  ApiFlexrixLaunchDemoRoute: typeof ApiFlexrixLaunchDemoRoute
  ApiOperatorCallbackRoute: typeof ApiOperatorCallbackRoute
  ApiOperatorGamesRoute: typeof ApiOperatorGamesRoute
  ApiOperatorLaunchRoute: typeof ApiOperatorLaunchRoute
  ApiOperatorPaymentsRoute: typeof ApiOperatorPaymentsRoute
  ApiOperatorSkillsRoute: typeof ApiOperatorSkillsRoute
  ApiOperatorStatusRoute: typeof ApiOperatorStatusRoute
  ApiOperatorWalletRoute: typeof ApiOperatorWalletRoute
  ApiSelftestSportTicketRoute: typeof ApiSelftestSportTicketRoute
  ApiSportsbookCallbackRoute: typeof ApiSportsbookCallbackRouteWithChildren
  ApiSportsbookEventsRoute: typeof ApiSportsbookEventsRoute
  ApiSportsbookScoresRoute: typeof ApiSportsbookScoresRoute
  ApiSportsbookSessionRoute: typeof ApiSportsbookSessionRoute
  ApiSportsbookSettleRoute: typeof ApiSportsbookSettleRoute
  ApiSportsbookSportsRoute: typeof ApiSportsbookSportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/affiliate': {
      id: '/_shell/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof ShellAffiliateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alerts': {
      id: '/_shell/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ShellAlertsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/aml': {
      id: '/_shell/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof ShellAmlRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/casino': {
      id: '/_shell/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof ShellCasinoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connect': {
      id: '/_shell/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ShellConnectRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fairness': {
      id: '/_shell/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof ShellFairnessRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/live': {
      id: '/_shell/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof ShellLiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/originals': {
      id: '/_shell/originals'
      path: '/originals'
      fullPath: '/originals'
      preLoaderRoute: typeof ShellOriginalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/privacy': {
      id: '/_shell/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ShellPrivacyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/promotions': {
      id: '/_shell/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof ShellPromotionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/redeem': {
      id: '/_shell/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof ShellRedeemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/responsible': {
      id: '/_shell/responsible'
      path: '/responsible'
      fullPath: '/responsible'
      preLoaderRoute: typeof ShellResponsibleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sports': {
      id: '/_shell/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof ShellSportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terms': {
      id: '/_shell/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShellTermsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/token': {
      id: '/_shell/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof ShellTokenRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vault': {
      id: '/_shell/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof ShellVaultRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vip': {
      id: '/_shell/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof ShellVipRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform': {
      id: '/api/platform'
      path: '/api/platform'
      fullPath: '/api/platform'
      preLoaderRoute: typeof ApiPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/treasury': {
      id: '/api/treasury'
      path: '/api/treasury'
      fullPath: '/api/treasury'
      preLoaderRoute: typeof ApiTreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/games/$id': {
      id: '/_shell/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof ShellGamesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/originals/$id': {
      id: '/_shell/originals/$id'
      path: '/$id'
      fullPath: '/originals/$id'
      preLoaderRoute: typeof ShellOriginalsIdRouteImport
      parentRoute: typeof ShellOriginalsRoute
    }
    '/_shell/play/$slug': {
      id: '/_shell/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof ShellPlaySlugRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sports/$id': {
      id: '/_shell/sports/$id'
      path: '/$id'
      fullPath: '/sports/$id'
      preLoaderRoute: typeof ShellSportsIdRouteImport
      parentRoute: typeof ShellSportsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/health': {
      id: '/api/bridge/health'
      path: '/api/bridge/health'
      fullPath: '/api/bridge/health'
      preLoaderRoute: typeof ApiBridgeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/webhook': {
      id: '/api/bridge/webhook'
      path: '/api/bridge/webhook'
      fullPath: '/api/bridge/webhook'
      preLoaderRoute: typeof ApiBridgeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flexrix/callback': {
      id: '/api/flexrix/callback'
      path: '/api/flexrix/callback'
      fullPath: '/api/flexrix/callback'
      preLoaderRoute: typeof ApiFlexrixCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flexrix/launch-demo': {
      id: '/api/flexrix/launch-demo'
      path: '/api/flexrix/launch-demo'
      fullPath: '/api/flexrix/launch-demo'
      preLoaderRoute: typeof ApiFlexrixLaunchDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/callback': {
      id: '/api/operator/callback'
      path: '/api/operator/callback'
      fullPath: '/api/operator/callback'
      preLoaderRoute: typeof ApiOperatorCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/games': {
      id: '/api/operator/games'
      path: '/api/operator/games'
      fullPath: '/api/operator/games'
      preLoaderRoute: typeof ApiOperatorGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/launch': {
      id: '/api/operator/launch'
      path: '/api/operator/launch'
      fullPath: '/api/operator/launch'
      preLoaderRoute: typeof ApiOperatorLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/payments': {
      id: '/api/operator/payments'
      path: '/api/operator/payments'
      fullPath: '/api/operator/payments'
      preLoaderRoute: typeof ApiOperatorPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/skills': {
      id: '/api/operator/skills'
      path: '/api/operator/skills'
      fullPath: '/api/operator/skills'
      preLoaderRoute: typeof ApiOperatorSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/status': {
      id: '/api/operator/status'
      path: '/api/operator/status'
      fullPath: '/api/operator/status'
      preLoaderRoute: typeof ApiOperatorStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/wallet': {
      id: '/api/operator/wallet'
      path: '/api/operator/wallet'
      fullPath: '/api/operator/wallet'
      preLoaderRoute: typeof ApiOperatorWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/health': {
      id: '/api/platform/health'
      path: '/health'
      fullPath: '/api/platform/health'
      preLoaderRoute: typeof ApiPlatformHealthRouteImport
      parentRoute: typeof ApiPlatformRoute
    }
    '/api/platform/whoami': {
      id: '/api/platform/whoami'
      path: '/whoami'
      fullPath: '/api/platform/whoami'
      preLoaderRoute: typeof ApiPlatformWhoamiRouteImport
      parentRoute: typeof ApiPlatformRoute
    }
    '/api/selftest/sport-ticket': {
      id: '/api/selftest/sport-ticket'
      path: '/api/selftest/sport-ticket'
      fullPath: '/api/selftest/sport-ticket'
      preLoaderRoute: typeof ApiSelftestSportTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/callback': {
      id: '/api/sportsbook/callback'
      path: '/api/sportsbook/callback'
      fullPath: '/api/sportsbook/callback'
      preLoaderRoute: typeof ApiSportsbookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/events': {
      id: '/api/sportsbook/events'
      path: '/api/sportsbook/events'
      fullPath: '/api/sportsbook/events'
      preLoaderRoute: typeof ApiSportsbookEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/scores': {
      id: '/api/sportsbook/scores'
      path: '/api/sportsbook/scores'
      fullPath: '/api/sportsbook/scores'
      preLoaderRoute: typeof ApiSportsbookScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/session': {
      id: '/api/sportsbook/session'
      path: '/api/sportsbook/session'
      fullPath: '/api/sportsbook/session'
      preLoaderRoute: typeof ApiSportsbookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/settle': {
      id: '/api/sportsbook/settle'
      path: '/api/sportsbook/settle'
      fullPath: '/api/sportsbook/settle'
      preLoaderRoute: typeof ApiSportsbookSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sportsbook/sports': {
      id: '/api/sportsbook/sports'
      path: '/api/sportsbook/sports'
      fullPath: '/api/sportsbook/sports'
      preLoaderRoute: typeof ApiSportsbookSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/sports/club/$slug': {
      id: '/_shell/sports/club/$slug'
      path: '/club/$slug'
      fullPath: '/sports/club/$slug'
      preLoaderRoute: typeof ShellSportsClubSlugRouteImport
      parentRoute: typeof ShellSportsRoute
    }
    '/_shell/sports/player/$slug': {
      id: '/_shell/sports/player/$slug'
      path: '/player/$slug'
      fullPath: '/sports/player/$slug'
      preLoaderRoute: typeof ShellSportsPlayerSlugRouteImport
      parentRoute: typeof ShellSportsRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/auth/google/diag': {
      id: '/api/auth/google/diag'
      path: '/diag'
      fullPath: '/api/auth/google/diag'
      preLoaderRoute: typeof ApiAuthGoogleDiagRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/sportsbook/callback/$action': {
      id: '/api/sportsbook/callback/$action'
      path: '/$action'
      fullPath: '/api/sportsbook/callback/$action'
      preLoaderRoute: typeof ApiSportsbookCallbackActionRouteImport
      parentRoute: typeof ApiSportsbookCallbackRoute
    }
  }
}

interface ShellOriginalsRouteChildren {
  ShellOriginalsIdRoute: typeof ShellOriginalsIdRoute
}

const ShellOriginalsRouteChildren: ShellOriginalsRouteChildren = {
  ShellOriginalsIdRoute: ShellOriginalsIdRoute,
}

const ShellOriginalsRouteWithChildren = ShellOriginalsRoute._addFileChildren(
  ShellOriginalsRouteChildren,
)

interface ShellSportsRouteChildren {
  ShellSportsIdRoute: typeof ShellSportsIdRoute
  ShellSportsClubSlugRoute: typeof ShellSportsClubSlugRoute
  ShellSportsPlayerSlugRoute: typeof ShellSportsPlayerSlugRoute
}

const ShellSportsRouteChildren: ShellSportsRouteChildren = {
  ShellSportsIdRoute: ShellSportsIdRoute,
  ShellSportsClubSlugRoute: ShellSportsClubSlugRoute,
  ShellSportsPlayerSlugRoute: ShellSportsPlayerSlugRoute,
}

const ShellSportsRouteWithChildren = ShellSportsRoute._addFileChildren(
  ShellSportsRouteChildren,
)

interface ShellRouteChildren {
  ShellAffiliateRoute: typeof ShellAffiliateRoute
  ShellAlertsRoute: typeof ShellAlertsRoute
  ShellAmlRoute: typeof ShellAmlRoute
  ShellCasinoRoute: typeof ShellCasinoRoute
  ShellConnectRoute: typeof ShellConnectRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFairnessRoute: typeof ShellFairnessRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellLiveRoute: typeof ShellLiveRoute
  ShellOriginalsRoute: typeof ShellOriginalsRouteWithChildren
  ShellPrivacyRoute: typeof ShellPrivacyRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellPromotionsRoute: typeof ShellPromotionsRoute
  ShellRedeemRoute: typeof ShellRedeemRoute
  ShellResponsibleRoute: typeof ShellResponsibleRoute
  ShellSportsRoute: typeof ShellSportsRouteWithChildren
  ShellTermsRoute: typeof ShellTermsRoute
  ShellTokenRoute: typeof ShellTokenRoute
  ShellVaultRoute: typeof ShellVaultRoute
  ShellVipRoute: typeof ShellVipRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellGamesIdRoute: typeof ShellGamesIdRoute
  ShellPlaySlugRoute: typeof ShellPlaySlugRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAffiliateRoute: ShellAffiliateRoute,
  ShellAlertsRoute: ShellAlertsRoute,
  ShellAmlRoute: ShellAmlRoute,
  ShellCasinoRoute: ShellCasinoRoute,
  ShellConnectRoute: ShellConnectRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFairnessRoute: ShellFairnessRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellLiveRoute: ShellLiveRoute,
  ShellOriginalsRoute: ShellOriginalsRouteWithChildren,
  ShellPrivacyRoute: ShellPrivacyRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellPromotionsRoute: ShellPromotionsRoute,
  ShellRedeemRoute: ShellRedeemRoute,
  ShellResponsibleRoute: ShellResponsibleRoute,
  ShellSportsRoute: ShellSportsRouteWithChildren,
  ShellTermsRoute: ShellTermsRoute,
  ShellTokenRoute: ShellTokenRoute,
  ShellVaultRoute: ShellVaultRoute,
  ShellVipRoute: ShellVipRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellGamesIdRoute: ShellGamesIdRoute,
  ShellPlaySlugRoute: ShellPlaySlugRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ApiPlatformRouteChildren {
  ApiPlatformHealthRoute: typeof ApiPlatformHealthRoute
  ApiPlatformWhoamiRoute: typeof ApiPlatformWhoamiRoute
}

const ApiPlatformRouteChildren: ApiPlatformRouteChildren = {
  ApiPlatformHealthRoute: ApiPlatformHealthRoute,
  ApiPlatformWhoamiRoute: ApiPlatformWhoamiRoute,
}

const ApiPlatformRouteWithChildren = ApiPlatformRoute._addFileChildren(
  ApiPlatformRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleDiagRoute: typeof ApiAuthGoogleDiagRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleDiagRoute: ApiAuthGoogleDiagRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

interface ApiSportsbookCallbackRouteChildren {
  ApiSportsbookCallbackActionRoute: typeof ApiSportsbookCallbackActionRoute
}

const ApiSportsbookCallbackRouteChildren: ApiSportsbookCallbackRouteChildren = {
  ApiSportsbookCallbackActionRoute: ApiSportsbookCallbackActionRoute,
}

const ApiSportsbookCallbackRouteWithChildren =
  ApiSportsbookCallbackRoute._addFileChildren(
    ApiSportsbookCallbackRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPlatformRoute: ApiPlatformRouteWithChildren,
  ApiTreasuryRoute: ApiTreasuryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiBridgeHealthRoute: ApiBridgeHealthRoute,
  ApiBridgeWebhookRoute: ApiBridgeWebhookRoute,
  ApiFlexrixCallbackRoute: ApiFlexrixCallbackRoute,
  ApiFlexrixLaunchDemoRoute: ApiFlexrixLaunchDemoRoute,
  ApiOperatorCallbackRoute: ApiOperatorCallbackRoute,
  ApiOperatorGamesRoute: ApiOperatorGamesRoute,
  ApiOperatorLaunchRoute: ApiOperatorLaunchRoute,
  ApiOperatorPaymentsRoute: ApiOperatorPaymentsRoute,
  ApiOperatorSkillsRoute: ApiOperatorSkillsRoute,
  ApiOperatorStatusRoute: ApiOperatorStatusRoute,
  ApiOperatorWalletRoute: ApiOperatorWalletRoute,
  ApiSelftestSportTicketRoute: ApiSelftestSportTicketRoute,
  ApiSportsbookCallbackRoute: ApiSportsbookCallbackRouteWithChildren,
  ApiSportsbookEventsRoute: ApiSportsbookEventsRoute,
  ApiSportsbookScoresRoute: ApiSportsbookScoresRoute,
  ApiSportsbookSessionRoute: ApiSportsbookSessionRoute,
  ApiSportsbookSettleRoute: ApiSportsbookSettleRoute,
  ApiSportsbookSportsRoute: ApiSportsbookSportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
