/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAffiliateRouteImport } from './routes/_shell/affiliate'
import { Route as ShellAlertsRouteImport } from './routes/_shell/alerts'
import { Route as ShellAmlRouteImport } from './routes/_shell/aml'
import { Route as ShellCasinoRouteImport } from './routes/_shell/casino'
import { Route as ShellConnectRouteImport } from './routes/_shell/connect'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellFairnessRouteImport } from './routes/_shell/fairness'
import { Route as ShellHelpRouteImport } from './routes/_shell/help'
import { Route as ShellLiveRouteImport } from './routes/_shell/live'
import { Route as ShellPrivacyRouteImport } from './routes/_shell/privacy'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellPromotionsRouteImport } from './routes/_shell/promotions'
import { Route as ShellRedeemRouteImport } from './routes/_shell/redeem'
import { Route as ShellResponsibleRouteImport } from './routes/_shell/responsible'
import { Route as ShellSportsRouteImport } from './routes/_shell/sports'
import { Route as ShellTermsRouteImport } from './routes/_shell/terms'
import { Route as ShellTokenRouteImport } from './routes/_shell/token'
import { Route as ShellVaultRouteImport } from './routes/_shell/vault'
import { Route as ShellVipRouteImport } from './routes/_shell/vip'
import { Route as ShellGamesIdRouteImport } from './routes/_shell/games.$id'
import { Route as ShellSportsIdRouteImport } from './routes/_shell/sports.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOperatorCallbackRouteImport } from './routes/api/operator/callback'
import { Route as ApiOperatorGamesRouteImport } from './routes/api/operator/games'
import { Route as ApiOperatorLaunchRouteImport } from './routes/api/operator/launch'
import { Route as ApiOperatorPaymentsRouteImport } from './routes/api/operator/payments'
import { Route as ApiOperatorSkillsRouteImport } from './routes/api/operator/skills'
import { Route as ApiOperatorWalletRouteImport } from './routes/api/operator/wallet'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAffiliateRoute = ShellAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlertsRoute = ShellAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAmlRoute = ShellAmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCasinoRoute = ShellCasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectRoute = ShellConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFairnessRoute = ShellFairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLiveRoute = ShellLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPrivacyRoute = ShellPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPromotionsRoute = ShellPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRedeemRoute = ShellRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResponsibleRoute = ShellResponsibleRouteImport.update({
  id: '/responsible',
  path: '/responsible',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSportsRoute = ShellSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTermsRoute = ShellTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTokenRoute = ShellTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVaultRoute = ShellVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVipRoute = ShellVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGamesIdRoute = ShellGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSportsIdRoute = ShellSportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellSportsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorCallbackRoute = ApiOperatorCallbackRouteImport.update({
  id: '/api/operator/callback',
  path: '/api/operator/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorGamesRoute = ApiOperatorGamesRouteImport.update({
  id: '/api/operator/games',
  path: '/api/operator/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorLaunchRoute = ApiOperatorLaunchRouteImport.update({
  id: '/api/operator/launch',
  path: '/api/operator/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorPaymentsRoute = ApiOperatorPaymentsRouteImport.update({
  id: '/api/operator/payments',
  path: '/api/operator/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorSkillsRoute = ApiOperatorSkillsRouteImport.update({
  id: '/api/operator/skills',
  path: '/api/operator/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorWalletRoute = ApiOperatorWalletRouteImport.update({
  id: '/api/operator/wallet',
  path: '/api/operator/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/affiliate': typeof ShellAffiliateRoute
  '/alerts': typeof ShellAlertsRoute
  '/aml': typeof ShellAmlRoute
  '/casino': typeof ShellCasinoRoute
  '/connect': typeof ShellConnectRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fairness': typeof ShellFairnessRoute
  '/help': typeof ShellHelpRoute
  '/live': typeof ShellLiveRoute
  '/privacy': typeof ShellPrivacyRoute
  '/profile': typeof ShellProfileRoute
  '/promotions': typeof ShellPromotionsRoute
  '/redeem': typeof ShellRedeemRoute
  '/responsible': typeof ShellResponsibleRoute
  '/sports': typeof ShellSportsRouteWithChildren
  '/terms': typeof ShellTermsRoute
  '/token': typeof ShellTokenRoute
  '/vault': typeof ShellVaultRoute
  '/vip': typeof ShellVipRoute
  '/games/$id': typeof ShellGamesIdRoute
  '/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/affiliate': typeof ShellAffiliateRoute
  '/alerts': typeof ShellAlertsRoute
  '/aml': typeof ShellAmlRoute
  '/casino': typeof ShellCasinoRoute
  '/connect': typeof ShellConnectRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fairness': typeof ShellFairnessRoute
  '/help': typeof ShellHelpRoute
  '/live': typeof ShellLiveRoute
  '/privacy': typeof ShellPrivacyRoute
  '/profile': typeof ShellProfileRoute
  '/promotions': typeof ShellPromotionsRoute
  '/redeem': typeof ShellRedeemRoute
  '/responsible': typeof ShellResponsibleRoute
  '/sports': typeof ShellSportsRouteWithChildren
  '/terms': typeof ShellTermsRoute
  '/token': typeof ShellTokenRoute
  '/vault': typeof ShellVaultRoute
  '/vip': typeof ShellVipRoute
  '/': typeof ShellIndexRoute
  '/games/$id': typeof ShellGamesIdRoute
  '/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/affiliate': typeof ShellAffiliateRoute
  '/_shell/alerts': typeof ShellAlertsRoute
  '/_shell/aml': typeof ShellAmlRoute
  '/_shell/casino': typeof ShellCasinoRoute
  '/_shell/connect': typeof ShellConnectRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/fairness': typeof ShellFairnessRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/live': typeof ShellLiveRoute
  '/_shell/privacy': typeof ShellPrivacyRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/promotions': typeof ShellPromotionsRoute
  '/_shell/redeem': typeof ShellRedeemRoute
  '/_shell/responsible': typeof ShellResponsibleRoute
  '/_shell/sports': typeof ShellSportsRouteWithChildren
  '/_shell/terms': typeof ShellTermsRoute
  '/_shell/token': typeof ShellTokenRoute
  '/_shell/vault': typeof ShellVaultRoute
  '/_shell/vip': typeof ShellVipRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/games/$id': typeof ShellGamesIdRoute
  '/_shell/sports/$id': typeof ShellSportsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/operator/callback': typeof ApiOperatorCallbackRoute
  '/api/operator/games': typeof ApiOperatorGamesRoute
  '/api/operator/launch': typeof ApiOperatorLaunchRoute
  '/api/operator/payments': typeof ApiOperatorPaymentsRoute
  '/api/operator/skills': typeof ApiOperatorSkillsRoute
  '/api/operator/wallet': typeof ApiOperatorWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/affiliate'
    | '/alerts'
    | '/aml'
    | '/casino'
    | '/connect'
    | '/dashboard'
    | '/fairness'
    | '/help'
    | '/live'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/redeem'
    | '/responsible'
    | '/sports'
    | '/terms'
    | '/token'
    | '/vault'
    | '/vip'
    | '/games/$id'
    | '/sports/$id'
    | '/api/auth/$'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/affiliate'
    | '/alerts'
    | '/aml'
    | '/casino'
    | '/connect'
    | '/dashboard'
    | '/fairness'
    | '/help'
    | '/live'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/redeem'
    | '/responsible'
    | '/sports'
    | '/terms'
    | '/token'
    | '/vault'
    | '/vip'
    | '/'
    | '/games/$id'
    | '/sports/$id'
    | '/api/auth/$'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/wallet'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/affiliate'
    | '/_shell/alerts'
    | '/_shell/aml'
    | '/_shell/casino'
    | '/_shell/connect'
    | '/_shell/dashboard'
    | '/_shell/fairness'
    | '/_shell/help'
    | '/_shell/live'
    | '/_shell/privacy'
    | '/_shell/profile'
    | '/_shell/promotions'
    | '/_shell/redeem'
    | '/_shell/responsible'
    | '/_shell/sports'
    | '/_shell/terms'
    | '/_shell/token'
    | '/_shell/vault'
    | '/_shell/vip'
    | '/_shell/'
    | '/_shell/games/$id'
    | '/_shell/sports/$id'
    | '/api/auth/$'
    | '/api/operator/callback'
    | '/api/operator/games'
    | '/api/operator/launch'
    | '/api/operator/payments'
    | '/api/operator/skills'
    | '/api/operator/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOperatorCallbackRoute: typeof ApiOperatorCallbackRoute
  ApiOperatorGamesRoute: typeof ApiOperatorGamesRoute
  ApiOperatorLaunchRoute: typeof ApiOperatorLaunchRoute
  ApiOperatorPaymentsRoute: typeof ApiOperatorPaymentsRoute
  ApiOperatorSkillsRoute: typeof ApiOperatorSkillsRoute
  ApiOperatorWalletRoute: typeof ApiOperatorWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/affiliate': {
      id: '/_shell/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof ShellAffiliateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alerts': {
      id: '/_shell/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ShellAlertsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/aml': {
      id: '/_shell/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof ShellAmlRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/casino': {
      id: '/_shell/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof ShellCasinoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connect': {
      id: '/_shell/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ShellConnectRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fairness': {
      id: '/_shell/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof ShellFairnessRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/live': {
      id: '/_shell/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof ShellLiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/privacy': {
      id: '/_shell/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ShellPrivacyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/promotions': {
      id: '/_shell/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof ShellPromotionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/redeem': {
      id: '/_shell/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof ShellRedeemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/responsible': {
      id: '/_shell/responsible'
      path: '/responsible'
      fullPath: '/responsible'
      preLoaderRoute: typeof ShellResponsibleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sports': {
      id: '/_shell/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof ShellSportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terms': {
      id: '/_shell/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShellTermsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/token': {
      id: '/_shell/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof ShellTokenRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vault': {
      id: '/_shell/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof ShellVaultRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vip': {
      id: '/_shell/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof ShellVipRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/games/$id': {
      id: '/_shell/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof ShellGamesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sports/$id': {
      id: '/_shell/sports/$id'
      path: '/$id'
      fullPath: '/sports/$id'
      preLoaderRoute: typeof ShellSportsIdRouteImport
      parentRoute: typeof ShellSportsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/callback': {
      id: '/api/operator/callback'
      path: '/api/operator/callback'
      fullPath: '/api/operator/callback'
      preLoaderRoute: typeof ApiOperatorCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/games': {
      id: '/api/operator/games'
      path: '/api/operator/games'
      fullPath: '/api/operator/games'
      preLoaderRoute: typeof ApiOperatorGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/launch': {
      id: '/api/operator/launch'
      path: '/api/operator/launch'
      fullPath: '/api/operator/launch'
      preLoaderRoute: typeof ApiOperatorLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/payments': {
      id: '/api/operator/payments'
      path: '/api/operator/payments'
      fullPath: '/api/operator/payments'
      preLoaderRoute: typeof ApiOperatorPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/skills': {
      id: '/api/operator/skills'
      path: '/api/operator/skills'
      fullPath: '/api/operator/skills'
      preLoaderRoute: typeof ApiOperatorSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/wallet': {
      id: '/api/operator/wallet'
      path: '/api/operator/wallet'
      fullPath: '/api/operator/wallet'
      preLoaderRoute: typeof ApiOperatorWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellSportsRouteChildren {
  ShellSportsIdRoute: typeof ShellSportsIdRoute
}

const ShellSportsRouteChildren: ShellSportsRouteChildren = {
  ShellSportsIdRoute: ShellSportsIdRoute,
}

const ShellSportsRouteWithChildren = ShellSportsRoute._addFileChildren(
  ShellSportsRouteChildren,
)

interface ShellRouteChildren {
  ShellAffiliateRoute: typeof ShellAffiliateRoute
  ShellAlertsRoute: typeof ShellAlertsRoute
  ShellAmlRoute: typeof ShellAmlRoute
  ShellCasinoRoute: typeof ShellCasinoRoute
  ShellConnectRoute: typeof ShellConnectRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFairnessRoute: typeof ShellFairnessRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellLiveRoute: typeof ShellLiveRoute
  ShellPrivacyRoute: typeof ShellPrivacyRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellPromotionsRoute: typeof ShellPromotionsRoute
  ShellRedeemRoute: typeof ShellRedeemRoute
  ShellResponsibleRoute: typeof ShellResponsibleRoute
  ShellSportsRoute: typeof ShellSportsRouteWithChildren
  ShellTermsRoute: typeof ShellTermsRoute
  ShellTokenRoute: typeof ShellTokenRoute
  ShellVaultRoute: typeof ShellVaultRoute
  ShellVipRoute: typeof ShellVipRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellGamesIdRoute: typeof ShellGamesIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAffiliateRoute: ShellAffiliateRoute,
  ShellAlertsRoute: ShellAlertsRoute,
  ShellAmlRoute: ShellAmlRoute,
  ShellCasinoRoute: ShellCasinoRoute,
  ShellConnectRoute: ShellConnectRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFairnessRoute: ShellFairnessRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellLiveRoute: ShellLiveRoute,
  ShellPrivacyRoute: ShellPrivacyRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellPromotionsRoute: ShellPromotionsRoute,
  ShellRedeemRoute: ShellRedeemRoute,
  ShellResponsibleRoute: ShellResponsibleRoute,
  ShellSportsRoute: ShellSportsRouteWithChildren,
  ShellTermsRoute: ShellTermsRoute,
  ShellTokenRoute: ShellTokenRoute,
  ShellVaultRoute: ShellVaultRoute,
  ShellVipRoute: ShellVipRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellGamesIdRoute: ShellGamesIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOperatorCallbackRoute: ApiOperatorCallbackRoute,
  ApiOperatorGamesRoute: ApiOperatorGamesRoute,
  ApiOperatorLaunchRoute: ApiOperatorLaunchRoute,
  ApiOperatorPaymentsRoute: ApiOperatorPaymentsRoute,
  ApiOperatorSkillsRoute: ApiOperatorSkillsRoute,
  ApiOperatorWalletRoute: ApiOperatorWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
